### ISSUE TITLE
Python implementaion

### ISSUE THREAD

**Issue by ajasja** [YangLiuLab/AIM#4]
Do you know of a Python implementation of AIM? 
Matlab is licensed and sometimes hard to run (for example we don't have a license), but Python is ubiquitous in scientific data analysis these days.

**Comment by YangLiuLab** [comment]
Some group is working on the python implementation of AIM. Once they are completed, they will share the update.

**Comment by ajasja** [comment]
Perfect, sounds good. We tried the matlab version and it works great.

**Comment by ajasja** [comment]
There is an AIM implementation in Picasso now. https://github.com/jungmannlab/picasso/pull/483/commits/d52fd18e07bfa1e5d623b8a98986661df38be0f3 

The speed of science progress these days is really amazing!
